package.json
project.yaml
schema.graphql
src/config.ts
src/helpers/errorHandler.ts
src/helpers/timekeeper.ts
src/helpers/types.ts
src/mappings/blocks.ts
src/mappings/epochs.ts
src/mappings/orders.ts
src/mappings/pools.ts
yarn.lock

Handling of total debt ans starting of Timekeeper

---

src/mappings/blocks.ts
src/mappings/epochs.ts
src/mappings/orders.ts
src/mappings/pools.ts

attach handlers to generic errorHandler promise catcher

---

project.yaml
schema.graphql
src/helpers/errorHandler.ts
src/helpers/stateSnapshot.ts
src/mappings/blocks.ts
src/mappings/pools.ts

23 calculate total borrowings + number of loans

---

package.json
schema.graphql
src/mappings/blocks.ts
src/mappings/tranches.ts
yarn.lock

28 Compute yields for tranches

---

.github/workflows/deploy-staging.yml
.github/workflows/test.yml

32 provide staging deployment backend

---

src/mappings/handlers/poolsHandlers.ts

extend epoch execution to carry over unfulfilled orders

---

project.yaml
schema.graphql
src/helpers/types.ts
src/mappings/handlers/poolsHandlers.ts
src/mappings/services/epochService.ts
src/mappings/services/investorTransactionService.ts
src/mappings/services/outstandingOrderService.ts

build: implement single investment orders fulfilment 

---

schema.graphql
src/mappings/services/investorTransactionService.ts

feat: investor transaction references in epoches

---

schema.graphql
src/config.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/services/epochService.ts
src/mappings/services/investorTransactionService.ts
src/mappings/services/outstandingOrderService.ts
src/mappings/services/poolService.ts
src/mappings/services/trancheService.ts

feat: add computation of pool value in indexer

---

project.yaml

feat: include modulo filter for block handler and update indexer version

---

project.yaml
src/mappings/handlers/blockHandlers.ts
src/mappings/services/epochService.ts
src/mappings/services/trancheService.ts

70 set initial token price for yield since inception calcs to 100 per default

---

.github/workflows/deploy.yml
project.yaml
src/chaintypes.ts
src/helpers/types.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/services/poolService.ts
src/mappings/services/trancheService.ts

73 fetch prices with rpc

---

src/mappings/handlers/poolsHandlers.ts
src/mappings/services/investorTransactionService.ts
src/mappings/services/outstandingOrderService.ts
src/mappings/services/trancheService.ts

fix: invest execution decimals and avoid empty transactions

---

schema.graphql
src/mappings/handlers/poolsHandlers.ts
src/mappings/services/epochService.ts
src/mappings/services/trancheService.ts

63 convert outflows to dai

---

.github/workflows/deploy.yml
src/helpers/stateSnapshot.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/services/poolService.ts
src/mappings/services/trancheService.ts

98 failing poolservicegettranchetokenprices causes period to be skipped for remaining pools

---

schema.graphql
src/mappings/services/epochService.ts

feat: aggregate total investments and repayments for epoches

---

schema.graphql
src/helpers/stateSnapshot.ts
src/helpers/types.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/handlers/poolsHandlers.ts
src/mappings/services/poolService.ts
src/mappings/services/trancheService.ts
yarn.lock

56 handle updates to pool information poolsupdated event

---

.github/workflows/deploy.yml
schema.graphql
src/mappings/handlers/loansHandlers.ts
src/mappings/handlers/poolsHandlers.ts
src/mappings/services/epochService.ts
src/mappings/services/poolService.ts
src/mappings/services/trancheService.ts

103 totalinvested  and totalredeemed  are missing in poolsnapshot

---

schema.graphql
src/mappings/handlers/blockHandlers.ts
src/mappings/handlers/loansHandlers.ts
src/mappings/services/loanService.ts
src/mappings/services/poolService.ts

#105 Index missing data items

---

project.yaml
schema.graphql
src/helpers/types.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/handlers/ormlTokensHandlers.ts
src/mappings/services/currencyBalance.ts
src/mappings/services/loanService.ts

104 track currency balances for accounts

---

project.yaml
schema.graphql
src/helpers/errorHandler.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/handlers/loansHandlers.ts
src/mappings/handlers/ormlTokensHandlers.ts
src/mappings/handlers/poolsHandlers.ts
src/mappings/services/accountService.ts
src/mappings/services/borrowerTransactionService.ts
src/mappings/services/currencyBalance.ts
src/mappings/services/currencyService.ts
src/mappings/services/epochService.ts
src/mappings/services/investorTransactionService.ts
src/mappings/services/loanService.ts
src/mappings/services/outstandingOrderService.ts
src/mappings/services/poolService.test.ts
src/mappings/services/poolService.ts
src/mappings/services/trancheBalanceService.ts
src/mappings/services/trancheService.test.ts
src/mappings/services/trancheService.ts

113 enhance standasdization and reusability of services

---

src/mappings/services/investorTransactionService.test.ts
src/mappings/services/loanService.test.ts
src/mappings/services/loanService.ts

implements #120
implements #121

unit testing for investortransactions and loans

---

project.yaml
src/mappings/handlers/loansHandlers.ts
src/mappings/services/epochService.ts

137 sumborrowedamount and sumrepaidamount are not increasing

---

chains/base.yaml
schema.graphql
src/helpers/types.ts
src/mappings/handlers/loansHandlers.ts
src/mappings/services/borrowerTransactionService.ts
src/mappings/services/loanService.ts
src/mappings/services/poolService.test.ts
src/mappings/services/poolService.ts

refactor: loan pallet

---

.github/workflows/subql_deploy_workflow.yaml
chains-evm/base.yaml
schema.graphql
src/api-interfaces/.gitignore
src/mappings/handlers/investmentsHandlers.ts
src/mappings/handlers/loansHandlers.ts
src/mappings/handlers/ormlTokensHandlers.ts
src/mappings/handlers/poolsHandlers.ts
src/mappings/handlers/proxyHandlers.ts
src/mappings/services/accountService.ts
src/mappings/services/currencyBalance.ts
src/mappings/services/currencyService.ts
src/mappings/services/evmAccountService.test.ts
src/mappings/services/evmAccountService.ts

167 extend data model to include evm accounts

---

chains-evm/eth/centrifuge.yaml
src/mappings/handlers/evmHandlers.ts
src/mappings/services/currencyBalanceService.ts
src/mappings/services/currencyService.ts

182 evm transfers not recorded

---

.github/workflows/subql_deploy_workflow.yaml
.github/workflows/test.yml
chains-evm/celo/centrifuge.yaml
subquery-multichain.yaml

187 add celo indexing

---

.envrc
chains-cfg/_root.yaml
chains-cfg/centrifuge.yaml
schema.graphql
src/mappings/handlers/ormlTokensHandlers.ts
src/mappings/services/currencyService.ts

190-Index-and-track-other-stablecoins-balances

---

schema.graphql
src/chaintypes.ts
src/helpers/types.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/services/loanService.test.ts
src/mappings/services/loanService.ts
src/mappings/services/poolService.ts

147-Fetch-outstandingDebt-with-runtime-call

---

schema.graphql
src/mappings/handlers/loansHandlers.ts
src/mappings/services/loanService.ts
src/mappings/services/poolService.test.ts
src/mappings/services/poolService.ts

feat: track loan KPIs in Pool and Poolsnapshots

---

jest/globals.js
src/mappings/services/trancheService.test.ts
src/mappings/services/trancheService.ts

fix token prices of non-mainnet chains

---

.envrc
chains-cfg/_root.yaml
src/helpers/types.ts
src/mappings/handlers/loansHandlers.ts
src/mappings/services/assetService.ts

feat: track amounts for DebtTransferred events (once added)

---

schema.graphql
src/mappings/services/poolFeeService.ts
src/mappings/services/poolFeeTransactionService.ts

fix: poolFee transactions for CHARGE and PAID not registered

---

chains-evm/eth/centrifuge.yaml
chains-tinlake/centrifuge.yaml
project-generator.sh
src/mappings/handlers/ethHandlers.ts

fix: unable to depoly tinlake in multichain

---

src/chaintypes.ts
src/helpers/types.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/handlers/ethHandlers.ts
src/mappings/handlers/evmHandlers.ts
src/mappings/services/poolFeeService.ts
src/mappings/services/poolService.ts
yarn.lock

218-track-poolFee-accruals

---

.envrc
docker/pg-Dockerfile
schema.graphql
src/chaintypes.ts
src/config.ts
src/helpers/paginatedGetter.ts
src/helpers/stateSnapshot.test.ts
src/helpers/stateSnapshot.ts
src/helpers/types.ts
src/index.ts
src/mappings/handlers/blockHandlers.ts
src/mappings/handlers/ethHandlers.ts
src/mappings/handlers/loansHandlers.ts
src/mappings/handlers/poolFeesHandlers.ts
src/mappings/handlers/poolsHandlers.ts
src/mappings/services/assetService.ts
src/mappings/services/outstandingOrderService.ts
src/mappings/services/poolFeeService.ts
src/mappings/services/poolService.ts
src/mappings/services/trancheService.ts
yarn.lock

220-Investigate-tinlake-indexing-issue

---

chains-cfg/_root.yaml
jest.config.ts
src/helpers/types.ts
src/mappings/handlers/poolsHandlers.ts
src/mappings/services/assetService.ts
src/mappings/services/poolService.ts

feat: track pool metadata updates

---

schema.graphql
src/mappings/handlers/blockHandlers.ts
src/mappings/handlers/poolFeesHandlers.ts
src/mappings/services/poolService.ts

feat: track sum fees on pool snapshots

---

schema.graphql
src/mappings/services/poolService.ts

feat: track deltaPortfolioValuationByPeriod
